services:
  km-ingredients-service:
    build: .
    container_name: km-ingredients-service

    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
#      DB_URL: ${DB_URL}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
#      MINIO_URL: ${MINIO_URL}
#      MINIO_ACCESS_NAME: ${MINIO_ACCESS_NAME}
#      MINIO_ACCESS_SECRET: ${MINIO_ACCESS_SECRET}
#      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      VAULT_TOKEN: ${VAULT_TOKEN}

  postgres:
    image: postgres:16
    container_name: ingredients-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ingredientsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
