name: Promote Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod
      image_tag:
        description: 'Image tag to deploy (e.g. SHA)'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/km-ingredients-service \
            km-ingredients-service=ivtheforth/km-ingredients-service:${{ github.event.inputs.image_tag }} \
            -n ${{ github.event.inputs.environment }}
